# Table and column name constants

class Tables:
    PLAY_BY_PLAY = "play_by_play"
    PLAYERS_ON_COURT_AT_START_OF_PERIOD = "players_on_court_at_start_of_period"
    ROTATIONS = "rotations"
    TEAM_GAME_LOG = "team_game_log"


class Columns:
    EVENTMSGTYPE = "EVENTMSGTYPE"
    EVENTMSGACTIONTYPE = "EVENTMSGACTIONTYPE"
    EVENTNUM = 'EVENTNUM'
    GAME_ID = "GAME_ID"
    ID = "id"
    IN_TIME_REAL = "IN_TIME_REAL"
    OUT_TIME_REAL = "OUT_TIME_REAL"
    PCTIMESTRING = "PCTIMESTRING"
    PERIOD = "PERIOD"
    PLAYER1_ID = "PLAYER1_ID"
    PLAYER1_TEAM_ID = "PLAYER1_TEAM_ID"
    PLAYER2_ID = "PLAYER2_ID"
    PLAYER2_TEAM_ID = "PLAYER2_TEAM_ID"
    PLAYER3_ID = "PLAYER3_ID"
    PLAYER3_TEAM_ID = "PLAYER3_TEAM_ID"
    PLAYER_FIRST_NAME = "PLAYER_FIRST"
    PLAYER_ID = "PLAYER_ID"
    PLAYER_LAST_NAME = "PLAYER_LAST"
    PLAYER_NAME = "PLAYER_NAME"
    SEASON = "SEASON"
    SEASON_TYPE = "SEASON_TYPE"
    SECONDS_FROM_START = "SECONDS_FROM_START"
    STINTS = "STINTS"
    TEAM1_PLAYER = "TEAM1_PLAYER"
    TEAM2_PLAYER = "TEAM2_PLAYER"
    TEAM_ID = "TEAM_ID"
    TEAM_NAME = "TEAM_NAME"
    # Add more column names as needed
